import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/features/provider/presentation/provider_notifier.dart';
// import 'package:frontend/features/provider/presentation/provider_state.dart';
import 'package:frontend/features/provider/data/provider_model.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';

// IMPORTANT: Ensure these imports point to your actual use-case class files.
// If your use-case classes are not structured like this, you need to adjust these imports.
import 'package:frontend/features/provider/domain/provider_usecases/get_all_providers.dart';
import 'package:frontend/features/provider/domain/provider_usecases/get_providers_by_category.dart';
import 'package:frontend/features/provider/domain/provider_usecases/get_provider_details.dart';
import 'package:frontend/features/provider/domain/provider_usecases/search_providers_by_name.dart';

// This annotation tells Mockito to generate mock classes for these concrete use-case classes.
@GenerateMocks([
  GetAllProviders,
  GetProvidersByCategory,
  GetProviderDetails,
  SearchProvidersByName,
])
import 'provider_notifier_test.mocks.dart'; // This file will be generated by build_runner

void main() {
  late ProviderNotifier notifier;
  // Declare the generated mock instances
  late MockGetAllProviders mockGetAllProviders;
  late MockGetProvidersByCategory mockGetProvidersByCategory;
  late MockGetProviderDetails mockGetProviderDetails;
  late MockSearchProvidersByName mockSearchProvidersByName;

  setUp(() {
    // Instantiate the generated mock classes
    mockGetAllProviders = MockGetAllProviders();
    mockGetProvidersByCategory = MockGetProvidersByCategory();
    mockGetProviderDetails = MockGetProviderDetails();
    mockSearchProvidersByName = MockSearchProvidersByName();

    notifier = ProviderNotifier(
      getAllProviders: mockGetAllProviders,
      getProvidersByCategory: mockGetProvidersByCategory,
      getProviderDetails: mockGetProviderDetails,
      searchProvidersByName: mockSearchProvidersByName,
    );
  });

  test('Initial state should be correct', () {
    // ASSERTION CHANGE: Check properties of the single ProviderState class
    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.providers, isEmpty);
    expect(notifier.state.selectedProvider, isNull);
    expect(notifier.state.errorMessage, isNull);
  });

  test('fetchAllProviders success', () async {
    // CORRECTED: Provide all required arguments for Provider constructor and use correct field names
    final mockProviders = [
      Provider(
        id: 1,
        userId: 1,
        phoneNumber: '0911223344',
        hourlyRate: '50.00',
        yearsOfExperience: 5,
        categoryId: 1, // categoryId is now nullable, but you can provide it
        serviceDescription: 'Test service description', // Use serviceDescription
        username: 'test_user', // Use username
        category: 'Test Category', // Use category
      )
    ];

    // Setup the mock: when the .call() method of the mock use-case is invoked, return mockProviders
    when(mockGetAllProviders.call()).thenAnswer((_) async => mockProviders);

    // Call the notifier's method
    await notifier.fetchAllProviders();

    // ASSERTION CHANGE: Check properties of the ProviderState
    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.providers, mockProviders);
    expect(notifier.state.errorMessage, isNull);
  });

  test('fetchAllProviders failure', () async {
    // Setup the mock: when the .call() method is invoked, throw an exception
    when(mockGetAllProviders.call()).thenThrow(Exception('Failed to load providers'));

    // Call the notifier's method
    await notifier.fetchAllProviders();

    // ASSERTION CHANGE: Check properties of the ProviderState
    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.providers, isEmpty); // Providers list should be empty on error
    expect(notifier.state.errorMessage, contains('Failed to load providers'));
  });

  test('fetchProvidersByCategory success', () async {
    final mockProviders = [
      Provider(
        id: 2,
        userId: 1,
        phoneNumber: '0911223344',
        hourlyRate: '60.00',
        yearsOfExperience: 3,
        categoryId: 2,
        serviceDescription: 'Category-specific service',
        username: 'cat_user',
        category: 'Category Two',
      )
    ];
    const categoryId = 2;
    when(mockGetProvidersByCategory.call(categoryId)).thenAnswer((_) async => mockProviders);

    await notifier.fetchProvidersByCategory(categoryId);

    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.providers, mockProviders);
    expect(notifier.state.errorMessage, isNull);
  });

  test('fetchProviderDetails success', () async {
    final mockProvider = Provider(
      id: 3,
      userId: 1,
      phoneNumber: '0911223344',
      hourlyRate: '70.00',
      yearsOfExperience: 10,
      categoryId: 1,
      serviceDescription: 'Detailed service info',
      username: 'detail_user',
      category: 'Main Category',
    );
    const providerId = 3;
    when(mockGetProviderDetails.call(providerId)).thenAnswer((_) async => mockProvider);

    await notifier.fetchProviderDetails(providerId);

    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.selectedProvider, mockProvider);
    expect(notifier.state.errorMessage, isNull);
    expect(notifier.state.providers, isEmpty); // Ensure providers list isn't affected by detail fetch
  });

  test('searchProviders success', () async {
    final mockProviders = [
      Provider(
        id: 4,
        userId: 1,
        phoneNumber: '0911223344',
        hourlyRate: '45.00',
        yearsOfExperience: 2,
        categoryId: 1,
        serviceDescription: 'Search result service',
        username: 'search_user',
        category: 'Search Category',
      )
    ];
    const query = 'searchterm';
    when(mockSearchProvidersByName.call(query)).thenAnswer((_) async => mockProviders);

    await notifier.searchProviders(query);

    expect(notifier.state.isLoading, isFalse);
    expect(notifier.state.providers, mockProviders);
    expect(notifier.state.errorMessage, isNull);
  });

  // You can add more tests for failure cases for each fetch method (e.g., fetchProvidersByCategory failure)
}